#!/bin/sh
#
# @name Simtoo Moment 007
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Michael Melchior <michael@aviate-it.com>
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output AUX1 servo 1
# @output AUX2 servo 2
#
. ${R}etc/init.d/rc.mc_defaults

set MIXER quad_x

set PWM_OUT 1234

# batteries
param set-default BAT1_CRIT_THR 0.15
param set-default BAT1_EMERGEN_THR 0.075
param set-default BAT1_LOW_THR 0.20

param set-default BAT1_CAPACITY 2900 // rated capacity of the simtoo smart battery
param set-default BAT1_N_CELLS 2 // the simtoo smart battery has two cells @4.35V
param set-default BAT_SOURCE 1 // external --> deprecated
param set-default BAT1_SOURCE 1 // external
param set-default BAT_R_INTERNAL 0.06 // needs to be verified! --> deprecated
param set-default BAT1_R_INTERNAL 0.06 // needs to be verified!
param set-default BAT_V_LOAD_DROP 1
param set-default BAT1_V_LOAD_DROP 1

# circuit breakers
param set-default CBRK_SUPPLY_CHK 894281 // turn off power supply check
param set-default CBRK_USB_CHK 197848

// https://docs.px4.io/master/en/getting_started/rc_transmitter_receiver.html
// Set to disable checking for a remote
// 0: RC Transmitter
// 1: Joystick / No RC Checks
// 2: Virtual Joystick
param set-default COM_RC_IN_MODE 1


# todo: enable for when tuning is done
param set-default MC_AIRMODE 0


# todo: check values
# 1: local_position_estimator, attitude_estimator_q (unsupported)
# 2: ekf2 (recommended)
# 3: Q attitude estimator (no position)
param set-default SYS_MC_EST_GROUP 2
param set-default EKF2_AID_MASK 1
param set-default EKF2_MAG_TYPE 0

# todo: tune values
param set-default IMU_DGYRO_CUTOFF 70
param set-default MC_PITCHRATE_D 0.002
param set-default MC_PITCHRATE_I 0.2
param set-default MC_PITCHRATE_P 0.07
param set-default MC_PITCH_P 6.5
param set-default MC_ROLLRATE_D 0.002
param set-default MC_ROLLRATE_I 0.2
param set-default MC_ROLLRATE_P 0.07
param set-default MC_ROLL_P 6.5
param set-default MC_YAW_P 3

# todo: check correct value
param set-default MPC_THR_HOVER 0.5
param set-default MPC_THR_MAX 1
param set-default MPC_Z_P 1.5
param set-default MPC_Z_VEL_P_ACC 8
param set-default MPC_Z_VEL_I_ACC 6
param set-default MPC_HOLD_MAX_XY 0.1
#param set-default MPC_MAX_FLOW_HGT 3

#MNT_DO_STAB 0
#MNT_MAN_PITCH 1
#MNT_MAN_ROLL 0
#MNT_MAN_YAW 0
#MNT_MODE_IN 0 // -1 Disabled, 0 Auto, 1 RC, 2 MAVLink_ROI, 3 MAVLink_DO_MOUNT, 4 MAVLink gimbal
#MNT_MODE_OUT 0 // 0 AUX
#MNT_RANGE_PITCH 90


# PWM rate [Hz]
param set-default PWM_MAIN_RATE 400

# PWM when disarmed
param set-default PWM_MAIN_DIS1 0
param set-default PWM_MAIN_DIS2 0
param set-default PWM_MAIN_DIS3 0
param set-default PWM_MAIN_DIS4 0
param set-default PWM_MAIN_DIS5 0
param set-default PWM_MAIN_DIS6 0

# PWM when armed
param set-default PWM_MAIN_MIN1 1000
param set-default PWM_MAIN_MIN2 1000
param set-default PWM_MAIN_MIN3 1000
param set-default PWM_MAIN_MIN4 1000

# max PWM, measured 1844, limited to 1800, though
param set-default PWM_MAIN_MAX1 1800 #1844
param set-default PWM_MAIN_MAX2 1800 #1844
param set-default PWM_MAIN_MAX3 1800 #1844
param set-default PWM_MAIN_MAX4 1800 #1844


param set-default RC_MAP_AUX2 0
param set-default RC_MAP_AUX1 1
param set-default RC_MAP_FLAPS 2
param set-default RC_MAP_THROTTLE 3
param set-default RC_MAP_YAW 4
param set-default RC_MAP_PITCH 5
param set-default RC_MAP_ROLL 6
param set-default RC_MAP_MODE_SW 7
param set-default RC_MAP_RETURN_SW 8
param set-default RC_MAP_LOITER_SW 9
param set-default RC_MAP_POSCTL_SW 10


# RC los failsafe mode after COM_RC_LOSS_T seconds
# 0: Disabled
# 1: Hold mode
# 2: Return mode
# 3: Land mode
# 4: RC Auto Recovery (CASA Outback Challenge rules)
# 5: Terminate
# 6: Lockdown
#param set-default COM_RC_LOSS_T 3
#param set-default NAV_RCL_ACT 1

